[package]
name = "hytale-manager"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Manage Hytale server installations, backups, and processes"

[[bin]]
name = "hy"
path = "src/main.rs"

[dependencies]
hy-backup = { workspace = true }
hy-cli = { workspace = true }
hy-dist = { workspace = true }
hy-instance = { workspace = true }
hy-java = { workspace = true }
hy-run = { workspace = true }

ansi-to-tui = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
anstream = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
indicatif = { workspace = true }
jiff = { workspace = true }
owo-colors = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
